services:
  postgres:
    image: postgres:16
    container_name: product-service_postgres
    environment:
      POSTGRES_DB: product-service_db
      POSTGRES_USER: product-service_user
      POSTGRES_PASSWORD: product-service_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product-service-network

volumes:
  postgres_data:

networks:
  product-service-network:
    name: product-service
    driver: bridge

